quarkus.http.port=${HTTP_PORT:8085}
quarkus.mongodb.connection-string=${MONGODB_URL:mongodb://localhost:27017}
quarkus.mongodb.database=${MONGODB_DATABASE:mvts_almacenamiento}
quarkus.oidc.auth-server-url=${KEYCLOAK_AUTH_URL:http://localhost:8180/realms/mvts}
quarkus.oidc.client-id=${KEYCLOAK_CLIENT_ID:almacenamiento-l}
quarkus.oidc.application-type=service
quarkus.oidc.tls.verification=none
