/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gerenciaproductos;

import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ángel
 */
public class frmGerenciaProductos extends javax.swing.JFrame {

    private String tokenCache = null;

    /**
     * Creates new form frmGerenciaProductos
     */
    public frmGerenciaProductos() {
        initComponents();

        tblDatos.setModel(new javax.swing.table.DefaultTableModel(
                new Object[]{"#", "Registro"}, 0));

        btnConectar.addActionListener(e -> cargarDatos());
        btnRefrescar.addActionListener(e -> cargarDatos());

        new java.util.Timer(true).scheduleAtFixedRate(new java.util.TimerTask() {
            @Override
            public void run() {
                cargarDatos();
            }
        }, 10000, 10000);
    }

    private String obtenerToken() throws Exception {
        String TOKEN_URL = "http://" + txtHost.getText()
                + ":8180/realms/mvts/protocol/openid-connect/token";
        
        String form = "grant_type=password"
                + "&client_id=" + java.net.URLEncoder.encode("mvts-gerencia-cli", java.nio.charset.StandardCharsets.UTF_8)
                + "&username=" + java.net.URLEncoder.encode("gerencia-productos", java.nio.charset.StandardCharsets.UTF_8)
                + "&password=" + java.net.URLEncoder.encode("gerencia123", java.nio.charset.StandardCharsets.UTF_8);

        java.net.http.HttpClient cliente = java.net.http.HttpClient.newHttpClient();
        java.net.http.HttpRequest req = java.net.http.HttpRequest.newBuilder()
                .uri(java.net.URI.create(TOKEN_URL))
                .header("Content-Type", "application/x-www-form-urlencoded")
                .POST(java.net.http.HttpRequest.BodyPublishers.ofString(form))
                .build();

        java.net.http.HttpResponse<String> resp = cliente.send(
                req, java.net.http.HttpResponse.BodyHandlers.ofString());

        if (resp.statusCode() != 200) {
            throw new Exception("Token fallido. HTTP " + resp.statusCode());
        }

        java.util.regex.Matcher m = java.util.regex.Pattern
                .compile("\"access_token\"\\s*:\\s*\"([^\"]+)\"")
                .matcher(resp.body());
        if (!m.find()) {
            throw new Exception("No se encontró access_token");
        }

        return m.group(1);
    }

    private String llamarEndpoint(String token) throws Exception {
        String url = "http://" + txtHost.getText() + "/api/reportes/productos";

        java.net.http.HttpClient cliente = java.net.http.HttpClient.newHttpClient();
        java.net.http.HttpRequest req = java.net.http.HttpRequest.newBuilder()
                .uri(java.net.URI.create(url))
                .header("Authorization", "Bearer " + token)
                .GET()
                .build();

        java.net.http.HttpResponse<String> resp = cliente.send(
                req, java.net.http.HttpResponse.BodyHandlers.ofString());

        if (resp.statusCode() != 200) {
            throw new Exception("HTTP " + resp.statusCode());
        }

        return resp.body();
    }

    private void cargarDatos() {
        new Thread(() -> {
            try {
                if (tokenCache == null) {
                    tokenCache = obtenerToken();
                }

                String json = llamarEndpoint(tokenCache);
                
                json = json.trim().replaceAll("^\\[|\\]$", "");
                String[] items = json.split(",(?=(?:[^\"]*\"[^\"]*\")*[^\"]*$)");

                DefaultTableModel modelo = (DefaultTableModel) tblDatos.getModel();
                SwingUtilities.invokeLater(() -> {
                    modelo.setRowCount(0);
                    for (int i = 0; i < items.length; i++) {
                        String val = items[i].trim().replaceAll("^\"|\"$", "");
                        modelo.addRow(new Object[]{i + 1, val});
                    }
                    lblEstado.setText("Actualizado: " + new java.text.SimpleDateFormat("HH:mm:ss").format(new java.util.Date()));
                    lblTotal.setText("Total: " + items.length);
                });

            } catch (Exception ex) {
                tokenCache = null; // si falla, fuerza re-login en el siguiente intento
                SwingUtilities.invokeLater(() -> lblEstado.setText("Error: " + ex.getMessage()));
            }
        }).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelNorte = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtHost = new javax.swing.JTextField();
        btnConectar = new javax.swing.JButton();
        btnRefrescar = new javax.swing.JButton();
        lblEstado = new javax.swing.JLabel();
        centro = new javax.swing.JScrollPane();
        tblDatos = new javax.swing.JTable();
        panelSur = new javax.swing.JPanel();
        lblTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gerencia Productos — MVTS");
        setResizable(false);

        panelNorte.setBackground(new java.awt.Color(236, 240, 241));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Host Nginx:");
        panelNorte.add(jLabel1);

        txtHost.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtHost.setMinimumSize(new java.awt.Dimension(130, 22));
        txtHost.setPreferredSize(new java.awt.Dimension(130, 32));
        panelNorte.add(txtHost);

        btnConectar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnConectar.setText("Conectar");
        panelNorte.add(btnConectar);

        btnRefrescar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnRefrescar.setText("Refrescar");
        panelNorte.add(btnRefrescar);

        lblEstado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblEstado.setText("ESTADO");
        panelNorte.add(lblEstado);

        tblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "#", "Payload (registro)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        centro.setViewportView(tblDatos);

        panelSur.setBackground(new java.awt.Color(236, 240, 241));

        lblTotal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTotal.setText("Total: 0");
        panelSur.add(lblTotal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelNorte, javax.swing.GroupLayout.DEFAULT_SIZE, 791, Short.MAX_VALUE)
            .addComponent(panelSur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(centro)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelNorte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(centro, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelSur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmGerenciaProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmGerenciaProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmGerenciaProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmGerenciaProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmGerenciaProductos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConectar;
    private javax.swing.JButton btnRefrescar;
    private javax.swing.JScrollPane centro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JPanel panelNorte;
    private javax.swing.JPanel panelSur;
    private javax.swing.JTable tblDatos;
    private javax.swing.JTextField txtHost;
    // End of variables declaration//GEN-END:variables
}
