# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/properties.properties to edit this template

quarkus.http.port=${HTTP_PORT:8081}
quarkus.grpc.server.port=${GRPC_PORT:9000}
quarkus.grpc.server.use-separate-server=false

quarkus.rabbitmq.devservices.enabled=false
rabbitmq-host=${RABBITMQ_HOST:localhost}
rabbitmq-port=${RABBITMQ_PORT:5672}
rabbitmq-username=${RABBITMQ_USER:guest}
rabbitmq-password=${RABBITMQ_PASS:guest}

quarkus.datasource.db-kind=mysql
quarkus.datasource.username=${MYSQL_USER:root}
quarkus.datasource.password=${MYSQL_PASSWORD:1234}
quarkus.datasource.jdbc.url=jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:mvts_topologia}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Hermosillo

quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=false
