quarkus.http.port=${HTTP_PORT:8086}
quarkus.rabbitmq.devservices.enabled=false

rabbitmq-host=${RABBITMQ_HOST:localhost}
rabbitmq-port=${RABBITMQ_PORT:5672}
rabbitmq-username=${RABBITMQ_USER:guest}
rabbitmq-password=${RABBITMQ_PASS:guest}

quarkus.mongodb.connection-string=${MONGODB_URL:mongodb://localhost:27017}
quarkus.mongodb.database=${MONGODB_DATABASE:mvts_almacenamiento}

mp.messaging.incoming.congestiones-in.connector=smallrye-rabbitmq
mp.messaging.incoming.congestiones-in.exchange.name=mina.exchange.principal
mp.messaging.incoming.congestiones-in.exchange.type=topic
mp.messaging.incoming.congestiones-in.queue.name=cola_congestiones_escritura
mp.messaging.incoming.congestiones-in.routing-keys=mina.congestiones.#
mp.messaging.incoming.congestiones-in.auto-acknowledgement=false
mp.messaging.incoming.congestiones-in.failure-strategy=requeue

mp.messaging.incoming.productos-in.connector=smallrye-rabbitmq
mp.messaging.incoming.productos-in.exchange.name=amq.topic
mp.messaging.incoming.productos-in.exchange.type=topic
mp.messaging.incoming.productos-in.queue.name=cola_productos_escritura
mp.messaging.incoming.productos-in.routing-keys=mina.vehiculos.descarga.#
mp.messaging.incoming.productos-in.auto-acknowledgement=false
mp.messaging.incoming.productos-in.failure-strategy=requeue
