
# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/properties.properties to edit this template

quarkus.http.port=${HTTP_PORT:8082}
quarkus.grpc.server.port=${GRPC_PORT:9001}
quarkus.grpc.server.use-separate-server=false

# Configuramos el cliente gRPC que llamaremos "cliente-topologia"
quarkus.grpc.clients.cliente-topologia.host=${TOPOLOGIA_HOST:localhost}
quarkus.grpc.clients.cliente-topologia.port=${TOPOLOGIA_PORT:8081}

# Desactivamos TLS temporalmente para desarrollo local
quarkus.grpc.clients.cliente-topologia.plain-text=true

quarkus.rabbitmq.devservices.enabled=false
rabbitmq-host=${RABBITMQ_HOST:localhost}
rabbitmq-port=${RABBITMQ_PORT:5672}
rabbitmq-username=${RABBITMQ_USER:guest}
rabbitmq-password=${RABBITMQ_PASS:guest}

# Rabbit
mp.messaging.incoming.vehiculos-in.connector=smallrye-rabbitmq
mp.messaging.incoming.vehiculos-in.exchange.name=${VEHICULOS_EXCHANGE:amq.topic}
mp.messaging.incoming.vehiculos-in.exchange.type=${VEHICULOS_EXCHANGE_TYPE:topic}
mp.messaging.incoming.vehiculos-in.routing-keys=${VEHICULOS_ROUTING_KEYS:mineria.vehiculos.#}

# Le damos un nombre a la cola para identificarla en la interfaz de RabbitMQ
mp.messaging.incoming.vehiculos-in.queue.name=cola.congestiones.vehiculos

# RabbitMQ moderno ya no permite colas transitorias no exclusivas.
# Para la POC la dejamos durable para evitar rechazos del broker.
mp.messaging.incoming.vehiculos-in.queue.durable=true
mp.messaging.incoming.vehiculos-in.queue.auto-delete=false

# Nuevo Cliente Notificaciones
quarkus.grpc.clients.cliente-notificaciones.host=${NOTIFICACIONES_HOST:localhost}
quarkus.grpc.clients.cliente-notificaciones.port=${NOTIFICACIONES_PORT:8083}
quarkus.grpc.clients.cliente-notificaciones.plain-text=true

# Almacenamiento
mp.messaging.outgoing.congestiones-out.connector=smallrye-rabbitmq
mp.messaging.outgoing.congestiones-out.exchange.name=mina.exchange.principal
mp.messaging.outgoing.congestiones-out.default-routing-key=mina.congestiones.alerta
